// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6bSDJQPAIkx2xrNLGG1Yfcr2V09-Bas',
    appId: '1:1048523886554:web:d5c6bef694df7d08347ae3',
    messagingSenderId: '1048523886554',
    projectId: 'photoplay-644a4',
    authDomain: 'photoplay-644a4.firebaseapp.com',
    storageBucket: 'photoplay-644a4.appspot.com',
    measurementId: 'G-WBDY3JN51P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKyK9cN9bdDKRfbRzGdsY-8qPtS1Ekro',
    appId: '1:1048523886554:android:c7a4580561953cea347ae3',
    messagingSenderId: '1048523886554',
    projectId: 'photoplay-644a4',
    storageBucket: 'photoplay-644a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-9_lUyTPZpMiegwg6PP8cGams490rfQ',
    appId: '1:1048523886554:ios:b03195caa49fbae4347ae3',
    messagingSenderId: '1048523886554',
    projectId: 'photoplay-644a4',
    storageBucket: 'photoplay-644a4.appspot.com',
    iosClientId: '1048523886554-fbh4s4bt7bfhdm1oropg2tn72outvues.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-9_lUyTPZpMiegwg6PP8cGams490rfQ',
    appId: '1:1048523886554:ios:b03195caa49fbae4347ae3',
    messagingSenderId: '1048523886554',
    projectId: 'photoplay-644a4',
    storageBucket: 'photoplay-644a4.appspot.com',
    iosClientId: '1048523886554-fbh4s4bt7bfhdm1oropg2tn72outvues.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoplay',
  );
}
